import React from 'react';

const TermsConditions = () => {
  return (
    <div className="bg-gray-950 text-gray-300 py-12 px-6 md:px-12 lg:px-20 font-sans selection:bg-cyan-900 selection:text-cyan-100">
      <div className="max-w-4xl mx-auto space-y-12 pb-12">
        
        {/* Header Section */}
        <div className="space-y-4 animate-fade-in-up">
          <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-600 drop-shadow-[0_0_15px_rgba(34,211,238,0.3)]">
            Terms & Conditions
          </h1>
          <p className="text-sm md:text-base text-gray-500 font-mono">
            Last Updated: {new Date().toLocaleDateString()}
          </p>
          <p className="text-lg text-gray-400">
            Welcome to AlgoSay. By accessing or using our platform, you agree to be bound by these terms. Please read them carefully.
          </p>
        </div>

        {/* Content Container */}
        <div className="bg-gray-900/40 border border-gray-800 rounded-2xl p-6 md:p-10 space-y-10 shadow-xl backdrop-blur-sm">
          
          {/* Section 1: Services */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-cyan-400 flex items-center gap-3">
              <span className="w-6 h-[2px] bg-cyan-400 shadow-[0_0_10px_rgba(34,211,238,0.8)]"></span>
              1. Description of Services (Backtesting Only)
            </h2>
            <p className="text-gray-300 leading-relaxed">
              AlgoSay is a software-as-a-service (SaaS) platform providing quantitative historical backtesting, strategy formulation, and data analytics tools for the Indian equity and derivatives markets. 
              <br/><br/>
              <strong className="text-white">Important Notice:</strong> AlgoSay is strictly a historical simulation and research tool. We do not provide live market trading, order execution, broker API integrations, or automated live order routing. All analytics are based purely on past historical datasets.
            </p>
          </section>

          {/* Section 2: SEBI Disclaimer (CRUCIAL) */}
          <section className="space-y-4 bg-red-950/20 border-l-4 border-red-500 p-6 rounded-r-lg">
            <h2 className="text-2xl font-semibold text-red-400 flex items-center gap-3">
              <span className="w-6 h-[2px] bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.8)]"></span>
              2. Not Financial Advice (SEBI Disclaimer)
            </h2>
            <div className="text-gray-300 leading-relaxed space-y-3 font-mono text-sm md:text-base">
              <p>
                <strong>AlgoSay is NOT a SEBI-registered Investment Advisor, Research Analyst, or Broker-Dealer.</strong>
              </p>
              <p>
                The platform, including its AI diagnostics, is solely for educational, analytical, and backtesting purposes. Historical performance generated by backtesting simulations does not guarantee future results. Real-world trading involves high market risks, and since our platform does not execute live trades, users are entirely responsible for their own financial decisions.
              </p>
            </div>
          </section>

          {/* Section 3: User Accounts */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-purple-400 flex items-center gap-3">
              <span className="w-6 h-[2px] bg-purple-400 shadow-[0_0_10px_rgba(168,85,247,0.8)]"></span>
              3. User Accounts & Security
            </h2>
            <p className="text-gray-300 leading-relaxed">
              To access our platform, you must create an account via Firebase authentication (Google OAuth or Email/Password). You are responsible for maintaining the confidentiality of your login credentials. AlgoSay reserves the right to terminate accounts that violate these terms or engage in platform misuse.
            </p>
          </section>

          {/* Section 4: Payments & Credits */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-blue-400 flex items-center gap-3">
              <span className="w-6 h-[2px] bg-blue-400 shadow-[0_0_10px_rgba(59,130,246,0.8)]"></span>
              4. Subscriptions, Payments & Credits
            </h2>
            <div className="text-gray-300 leading-relaxed">
              <p>AlgoSay operates on a subscription and pay-as-you-go credit token model for running backtests. All payments are processed securely via Razorpay.</p>
              <ul className="list-disc list-inside mt-3 space-y-2 text-gray-400">
                <li>Credits purchased are added to your AlgoSay account and are non-transferable.</li>
                <li>Subscription plans auto-renew unless cancelled prior to the billing cycle.</li>
                <li>For details on refunds, please refer to our refund policy.</li>
              </ul>
            </div>
          </section>

          {/* Section 5: Intellectual Property */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-cyan-400 flex items-center gap-3">
              <span className="w-6 h-[2px] bg-cyan-400 shadow-[0_0_10px_rgba(34,211,238,0.8)]"></span>
              5. Intellectual Property
            </h2>
            <p className="text-gray-300 leading-relaxed">
              All platform designs, code (including the React frontend, backend data pipelines, and multi-leg options backtesting simulation engines), graphics, and algorithms remain the exclusive property of AlgoSay. Your custom strategies saved in our database remain yours, but the underlying infrastructure processing them is our proprietary intellectual property.
            </p>
          </section>

          {/* Section 6: Limitation of Liability */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-gray-400 flex items-center gap-3">
              <span className="w-6 h-[2px] bg-gray-500"></span>
              6. Limitation of Liability
            </h2>
            <p className="text-gray-300 leading-relaxed">
              In no event shall AlgoSay, its founders, or affiliates be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use our backtesting tools, simulation downtime, or variances in historical market data streams.
            </p>
          </section>

        </div>

        {/* Footer Contact Info */}
        <div className="text-center text-gray-500 pt-8 border-t border-gray-800">
          <p>If you have any questions about these Terms, please contact us at <a href="mailto:support@algosay.com" className="text-cyan-400 hover:underline">support@algosay.com</a></p>
        </div>

      </div>
    </div>
  );
};

export default TermsConditions;